In [125]:
from pathlib import Path

import polars as pl

project_path = Path.cwd() / "output" / "project"

In [126]:
cnpt_name = "calcium ionized".replace(" ", "_").replace("/", "-")
cnpt_pattern = "(50808//Free Calcium)"

In [127]:
cnpt_directory = project_path / "workspace" / "concept" / cnpt_name / "1.0.0"

cnpt_paths = [str(p) for p in cnpt_directory.iterdir() if p.is_file()]

cnpt =  pl.scan_parquet(cnpt_paths[0])
cnpt = cnpt.with_columns(pl.col("time").dt.replace_time_zone("UTC"))
cnpt = cnpt.collect()

In [128]:
cnpt

shape: (370_407, 7)
┌────────────┬────────────────┬────────────────┬───────────────┬────────────┬──────────┬───────────┐
│ subject_id ┆ time           ┆ code           ┆ numeric_value ┆ text_value ┆ dataset  ┆ table     │
│ ---        ┆ ---            ┆ ---            ┆ ---           ┆ ---        ┆ ---      ┆ ---       │
│ i64        ┆ datetime[μs,   ┆ str            ┆ f32           ┆ str        ┆ str      ┆ str       │
│            ┆ UTC]           ┆                ┆               ┆            ┆          ┆           │
╞════════════╪════════════════╪════════════════╪═══════════════╪════════════╪══════════╪═══════════╡
│ 10000117   ┆ 2174-10-14     ┆ calcium_ionize ┆ 1.23          ┆ 1.23       ┆ mimic-iv ┆ labevents │
│            ┆ 14:52:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2175-01-27     ┆ calcium_ionize ┆ 1.2           ┆ 1.20       ┆ mimic-iv ┆ labevents │
│            ┆ 16:28:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 10001884   ┆ 2131-01-11     ┆ calcium_ionize ┆ 1.25          ┆ 1.25       ┆ mimic-iv ┆ labevents │
│            ┆ 06:37:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 10001884   ┆ 2131-01-13     ┆ calcium_ionize ┆ 1.17          ┆ 1.17       ┆ mimic-iv ┆ labevents │
│            ┆ 02:28:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 10002013   ┆ 2160-05-18     ┆ calcium_ionize ┆ 1.16          ┆ 1.16       ┆ mimic-iv ┆ labevents │
│            ┆ 09:19:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ …          ┆ …              ┆ …              ┆ …             ┆ …          ┆ …        ┆ …         │
│ 19999840   ┆ 2164-09-17     ┆ calcium_ionize ┆ 1.15          ┆ 1.15       ┆ mimic-iv ┆ labevents │
│            ┆ 08:11:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 19999840   ┆ 2164-09-17     ┆ calcium_ionize ┆ 1.08          ┆ 1.08       ┆ mimic-iv ┆ labevents │
│            ┆ 13:18:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 19999840   ┆ 2164-09-17     ┆ calcium_ionize ┆ 1.15          ┆ 1.15       ┆ mimic-iv ┆ labevents │
│            ┆ 13:34:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 19999840   ┆ 2164-09-17     ┆ calcium_ionize ┆ 1.1           ┆ 1.10       ┆ mimic-iv ┆ labevents │
│            ┆ 13:39:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
│ 19999987   ┆ 2145-11-02     ┆ calcium_ionize ┆ 1.12          ┆ 1.12       ┆ mimic-iv ┆ labevents │
│            ┆ 19:49:00 UTC   ┆ d//mmol/L      ┆               ┆            ┆          ┆           │
└────────────┴────────────────┴────────────────┴───────────────┴────────────┴──────────┴───────────┘

In [129]:
labevent = pl.scan_parquet(project_path / "workspace" / "extraction" / "mimic-iv" / "3.1" / "labevents" / "result.parquet")
data = labevent.filter(pl.col("code").str.contains(cnpt_pattern)).collect()

In [130]:
data.sort("time")

shape: (370_407, 7)
┌────────────┬──────────────┬────────────────────┬───────────────┬────────────┬──────────┬─────────┐
│ subject_id ┆ time         ┆ code               ┆ numeric_value ┆ text_value ┆ hadm_id  ┆ stay_id │
│ ---        ┆ ---          ┆ ---                ┆ ---           ┆ ---        ┆ ---      ┆ ---     │
│ i64        ┆ datetime[μs] ┆ str                ┆ f32           ┆ str        ┆ str      ┆ str     │
╞════════════╪══════════════╪════════════════════╪═══════════════╪════════════╪══════════╪═════════╡
│ 16904137   ┆ 2105-10-05   ┆ mimic-iv//3.1//lab ┆ 1.04          ┆ 1.04       ┆ 21081215 ┆ -1      │
│            ┆ 11:44:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16904137   ┆ 2105-10-05   ┆ mimic-iv//3.1//lab ┆ 0.99          ┆ ___        ┆ 21081215 ┆ -1      │
│            ┆ 12:41:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 11556680   ┆ 2109-06-27   ┆ mimic-iv//3.1//lab ┆ 1.16          ┆ 1.16       ┆ null     ┆ -1      │
│            ┆ 12:23:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 12418411   ┆ 2109-07-09   ┆ mimic-iv//3.1//lab ┆ 1.01          ┆ 1.01       ┆ null     ┆ -1      │
│            ┆ 11:03:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 12418411   ┆ 2109-07-09   ┆ mimic-iv//3.1//lab ┆ 1.15          ┆ 1.15       ┆ null     ┆ -1      │
│            ┆ 14:06:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ …          ┆ …            ┆ …                  ┆ …             ┆ …          ┆ …        ┆ …       │
│ 15173387   ┆ 2214-07-21   ┆ mimic-iv//3.1//lab ┆ 1.2           ┆ 1.20       ┆ 28006722 ┆ -1      │
│            ┆ 11:54:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 15173387   ┆ 2214-07-23   ┆ mimic-iv//3.1//lab ┆ 1.15          ┆ 1.15       ┆ 28006722 ┆ -1      │
│            ┆ 19:28:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 12965924   ┆ 2214-10-23   ┆ mimic-iv//3.1//lab ┆ 1.12          ┆ 1.12       ┆ null     ┆ -1      │
│            ┆ 06:27:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16573705   ┆ 2214-12-24   ┆ mimic-iv//3.1//lab ┆ 1.25          ┆ 1.25       ┆ null     ┆ -1      │
│            ┆ 04:42:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16573705   ┆ 2214-12-24   ┆ mimic-iv//3.1//lab ┆ 1.25          ┆ 1.25       ┆ null     ┆ -1      │
│            ┆ 09:02:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
└────────────┴──────────────┴────────────────────┴───────────────┴────────────┴──────────┴─────────┘

In [131]:
for e in data.unique("code")["code"]:
    print(e)

mimic-iv//3.1//labevents//result//50808//Free Calcium//mmol/L

In [132]:
ricu = pl.read_parquet("./data/cnpt_labevents.parquet")
ricu

FileNotFoundError: No such file or directory (os error 2): ./data/cnpt_labevents.parquet

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

In [ ]:
#ricu.sort("charttime_origin")

In [ ]:
ricu.join(cnpt, left_on=["subject_id", "charttime"], right_on=["subject_id", "time"], how="anti")

shape: (3_216_594, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ labevent_i ┆ subject_id ┆ hadm_id  ┆ specimen_ ┆ … ┆ ref_range ┆ flag     ┆ priority ┆ comments  │
│ d          ┆ ---        ┆ ---      ┆ id        ┆   ┆ _upper    ┆ ---      ┆ ---      ┆ ---       │
│ ---        ┆ i32        ┆ i32      ┆ ---       ┆   ┆ ---       ┆ str      ┆ str      ┆ str       │
│ i32        ┆            ┆          ┆ i32       ┆   ┆ f64       ┆          ┆          ┆           │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ 154        ┆ 10000032   ┆ 22595853 ┆ 86271148  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 181        ┆ 10000032   ┆ null     ┆ 19543630  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 190        ┆ 10000032   ┆ null     ┆ 58691952  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 403        ┆ 10000032   ┆ 29079034 ┆ 55621508  ┆ … ┆ 5.1       ┆ null     ┆ STAT     ┆ null      │
│ 451        ┆ 10000032   ┆ 29079034 ┆ 66433308  ┆ … ┆ 5.1       ┆ abnormal ┆ ROUTINE  ┆ null      │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …        ┆ …        ┆ …         │
│ 159057396  ┆ 19999987   ┆ 23865745 ┆ 34834852  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ HEMOLYSIS │
│            ┆            ┆          ┆           ┆   ┆           ┆          ┆          ┆ FALSELY   │
│            ┆            ┆          ┆           ┆   ┆           ┆          ┆          ┆ ELEVATES  │
│            ┆            ┆          ┆           ┆   ┆           ┆          ┆          ┆ K..       │
│ 159057461  ┆ 19999987   ┆ 23865745 ┆ 62584889  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 159057486  ┆ 19999987   ┆ 23865745 ┆ 45769962  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 159057509  ┆ 19999987   ┆ 23865745 ┆ 67447234  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 159057524  ┆ 19999987   ┆ 23865745 ┆ 55471641  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴──────────┴──────────┴───────────┘

In [ ]:
cnpt.join(ricu, left_on=["subject_id", "time"], right_on=["subject_id", "charttime"], how="anti")

shape: (99_599, 7)
┌────────────┬──────────────┬───────────────┬───────────────┬────────────┬──────────┬───────────┐
│ subject_id ┆ time         ┆ code          ┆ numeric_value ┆ text_value ┆ dataset  ┆ table     │
│ ---        ┆ ---          ┆ ---           ┆ ---           ┆ ---        ┆ ---      ┆ ---       │
│ i64        ┆ datetime[μs, ┆ str           ┆ f32           ┆ str        ┆ str      ┆ str       │
│            ┆ UTC]         ┆               ┆               ┆            ┆          ┆           │
╞════════════╪══════════════╪═══════════════╪═══════════════╪════════════╪══════════╪═══════════╡
│ 10000117   ┆ 2174-09-22   ┆ albumin//g/dL ┆ 4.7           ┆ 4.7        ┆ mimic-iv ┆ labevents │
│            ┆ 12:26:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2175-01-27   ┆ albumin//g/dL ┆ 4.7           ┆ 4.7        ┆ mimic-iv ┆ labevents │
│            ┆ 16:15:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2176-02-08   ┆ albumin//g/dL ┆ 4.9           ┆ 4.9        ┆ mimic-iv ┆ labevents │
│            ┆ 22:00:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2176-09-08   ┆ albumin//g/dL ┆ 4.9           ┆ 4.9        ┆ mimic-iv ┆ labevents │
│            ┆ 10:00:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2178-06-12   ┆ albumin//g/dL ┆ 4.8           ┆ 4.8        ┆ mimic-iv ┆ labevents │
│            ┆ 15:19:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ …          ┆ …            ┆ …             ┆ …             ┆ …          ┆ …        ┆ …         │
│ 19999784   ┆ 2119-06-27   ┆ albumin//g/dL ┆ 3.7           ┆ 3.7        ┆ mimic-iv ┆ labevents │
│            ┆ 05:40:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2119-07-07   ┆ albumin//g/dL ┆ 4.3           ┆ 4.3        ┆ mimic-iv ┆ labevents │
│            ┆ 17:30:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2123-04-12   ┆ albumin//g/dL ┆ 4.0           ┆ 4.0        ┆ mimic-iv ┆ labevents │
│            ┆ 12:28:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2123-05-08   ┆ albumin//g/dL ┆ 4.0           ┆ 4.0        ┆ mimic-iv ┆ labevents │
│            ┆ 10:00:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2124-07-22   ┆ albumin//g/dL ┆ 4.3           ┆ 4.3        ┆ mimic-iv ┆ labevents │
│            ┆ 15:25:00 UTC ┆               ┆               ┆            ┆          ┆           │
└────────────┴──────────────┴───────────────┴───────────────┴────────────┴──────────┴───────────┘

In [ ]:
# ricu.join(cnpt, left_on=["subject_id", "charttime", "valuenum"], right_on=["subject_id", "time", "numeric_value"], how="anti")

In [ ]:
# cnpt.join(ricu, left_on=["subject_id", "time", "numeric_value"], right_on=["subject_id", "charttime", "valuenum"], how="anti")