In [1]:
from pathlib import Path

import polars as pl

project_path = Path.cwd() / "output" / "project"

In [2]:
cnpt_name = "white_blood_cell_count".lower().replace(" ", "_").replace("/", "-")
cnpt_pattern = "(51301//White Blood Cells)"
size = 4157284

In [3]:
cnpt_directory = project_path / "workspace" / "concept" / cnpt_name / "1.0.0"

cnpt_paths = [str(p) for p in cnpt_directory.iterdir() if p.is_file()]

cnpt =  pl.scan_parquet(cnpt_paths[0])
cnpt = cnpt.with_columns(pl.col("time").dt.replace_time_zone("UTC"))
cnpt = cnpt.collect()

In [4]:
len(cnpt) == size

True

In [5]:
cnpt

shape: (4_157_284, 7)
┌────────────┬────────────────┬────────────────┬───────────────┬────────────┬──────────┬───────────┐
│ subject_id ┆ time           ┆ code           ┆ numeric_value ┆ text_value ┆ dataset  ┆ table     │
│ ---        ┆ ---            ┆ ---            ┆ ---           ┆ ---        ┆ ---      ┆ ---       │
│ i64        ┆ datetime[μs,   ┆ str            ┆ f32           ┆ str        ┆ str      ┆ str       │
│            ┆ UTC]           ┆                ┆               ┆            ┆          ┆           │
╞════════════╪════════════════╪════════════════╪═══════════════╪════════════╪══════════╪═══════════╡
│ 10000032   ┆ 2180-03-23     ┆ white_blood_ce ┆ 3.0           ┆ 3.0        ┆ mimic-iv ┆ labevents │
│            ┆ 11:51:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 10000032   ┆ 2180-05-06     ┆ white_blood_ce ┆ 5.0           ┆ 5.0        ┆ mimic-iv ┆ labevents │
│            ┆ 22:25:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 10000032   ┆ 2180-05-07     ┆ white_blood_ce ┆ 4.2           ┆ 4.2        ┆ mimic-iv ┆ labevents │
│            ┆ 05:05:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 10000032   ┆ 2180-06-22     ┆ white_blood_ce ┆ 5.1           ┆ 5.1        ┆ mimic-iv ┆ labevents │
│            ┆ 11:15:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 10000032   ┆ 2180-06-26     ┆ white_blood_ce ┆ 6.6           ┆ 6.6        ┆ mimic-iv ┆ labevents │
│            ┆ 16:10:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ …          ┆ …              ┆ …              ┆ …             ┆ …          ┆ …        ┆ …         │
│ 19999987   ┆ 2145-11-04     ┆ white_blood_ce ┆ 11.6          ┆ 11.6       ┆ mimic-iv ┆ labevents │
│            ┆ 10:40:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 19999987   ┆ 2145-11-05     ┆ white_blood_ce ┆ 10.0          ┆ 10.0       ┆ mimic-iv ┆ labevents │
│            ┆ 06:10:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 19999987   ┆ 2145-11-06     ┆ white_blood_ce ┆ 5.9           ┆ 5.9        ┆ mimic-iv ┆ labevents │
│            ┆ 10:07:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 19999987   ┆ 2145-11-07     ┆ white_blood_ce ┆ 5.0           ┆ 5.0        ┆ mimic-iv ┆ labevents │
│            ┆ 06:00:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
│ 19999987   ┆ 2145-11-09     ┆ white_blood_ce ┆ 5.7           ┆ 5.7        ┆ mimic-iv ┆ labevents │
│            ┆ 05:30:00 UTC   ┆ ll_count//K/uL ┆               ┆            ┆          ┆           │
└────────────┴────────────────┴────────────────┴───────────────┴────────────┴──────────┴───────────┘

In [6]:
labevent = pl.scan_parquet(project_path / "workspace" / "extraction" / "mimic-iv" / "3.1" / "labevents" / "result.parquet")
data = labevent.filter(pl.col("code").str.contains(cnpt_pattern)).collect()

In [7]:
data.sort("time")

shape: (4_157_284, 7)
┌────────────┬──────────────┬────────────────────┬───────────────┬────────────┬──────────┬─────────┐
│ subject_id ┆ time         ┆ code               ┆ numeric_value ┆ text_value ┆ hadm_id  ┆ stay_id │
│ ---        ┆ ---          ┆ ---                ┆ ---           ┆ ---        ┆ ---      ┆ ---     │
│ i64        ┆ datetime[μs] ┆ str                ┆ f32           ┆ str        ┆ str      ┆ str     │
╞════════════╪══════════════╪════════════════════╪═══════════════╪════════════╪══════════╪═════════╡
│ 16904137   ┆ 2105-01-19   ┆ mimic-iv//3.1//lab ┆ 7.2           ┆ 7.2        ┆ null     ┆ -1      │
│            ┆ 12:04:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16904137   ┆ 2105-02-02   ┆ mimic-iv//3.1//lab ┆ 8.9           ┆ 8.9        ┆ null     ┆ -1      │
│            ┆ 11:10:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16904137   ┆ 2105-04-06   ┆ mimic-iv//3.1//lab ┆ 7.7           ┆ 7.7        ┆ null     ┆ -1      │
│            ┆ 10:20:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16904137   ┆ 2105-10-04   ┆ mimic-iv//3.1//lab ┆ 9.6           ┆ 9.6        ┆ null     ┆ -1      │
│            ┆ 17:27:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16904137   ┆ 2105-10-05   ┆ mimic-iv//3.1//lab ┆ 11.5          ┆ 11.5       ┆ 21081215 ┆ -1      │
│            ┆ 01:41:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ …          ┆ …            ┆ …                  ┆ …             ┆ …          ┆ …        ┆ …       │
│ 16573705   ┆ 2215-01-01   ┆ mimic-iv//3.1//lab ┆ 4.7           ┆ 4.7        ┆ null     ┆ -1      │
│            ┆ 04:17:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16573705   ┆ 2215-01-01   ┆ mimic-iv//3.1//lab ┆ 4.8           ┆ 4.8        ┆ null     ┆ -1      │
│            ┆ 11:42:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16573705   ┆ 2215-01-02   ┆ mimic-iv//3.1//lab ┆ 5.5           ┆ 5.5        ┆ null     ┆ -1      │
│            ┆ 02:26:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16573705   ┆ 2215-01-03   ┆ mimic-iv//3.1//lab ┆ 4.3           ┆ 4.3        ┆ null     ┆ -1      │
│            ┆ 06:25:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
│ 16573705   ┆ 2215-01-12   ┆ mimic-iv//3.1//lab ┆ 3.4           ┆ 3.4        ┆ null     ┆ -1      │
│            ┆ 11:45:00     ┆ events//resu…      ┆               ┆            ┆          ┆         │
└────────────┴──────────────┴────────────────────┴───────────────┴────────────┴──────────┴─────────┘

In [8]:
for e in data.unique("code")["code"]:
    print(e)

mimic-iv//3.1//labevents//result//51301//White Blood Cells//K/uL
mimic-iv//3.1//labevents//result//51301//White Blood Cells

In [9]:
ricu = pl.read_parquet("./data/cnpt_labevents.parquet")
ricu

FileNotFoundError: No such file or directory (os error 2): ./data/cnpt_labevents.parquet

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'

In [ ]:
#ricu.sort("charttime_origin")

In [ ]:
ricu.join(cnpt, left_on=["subject_id", "charttime"], right_on=["subject_id", "time"], how="anti")

shape: (3_216_594, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ labevent_i ┆ subject_id ┆ hadm_id  ┆ specimen_ ┆ … ┆ ref_range ┆ flag     ┆ priority ┆ comments  │
│ d          ┆ ---        ┆ ---      ┆ id        ┆   ┆ _upper    ┆ ---      ┆ ---      ┆ ---       │
│ ---        ┆ i32        ┆ i32      ┆ ---       ┆   ┆ ---       ┆ str      ┆ str      ┆ str       │
│ i32        ┆            ┆          ┆ i32       ┆   ┆ f64       ┆          ┆          ┆           │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ 154        ┆ 10000032   ┆ 22595853 ┆ 86271148  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 181        ┆ 10000032   ┆ null     ┆ 19543630  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 190        ┆ 10000032   ┆ null     ┆ 58691952  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 403        ┆ 10000032   ┆ 29079034 ┆ 55621508  ┆ … ┆ 5.1       ┆ null     ┆ STAT     ┆ null      │
│ 451        ┆ 10000032   ┆ 29079034 ┆ 66433308  ┆ … ┆ 5.1       ┆ abnormal ┆ ROUTINE  ┆ null      │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …        ┆ …        ┆ …         │
│ 159057396  ┆ 19999987   ┆ 23865745 ┆ 34834852  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ HEMOLYSIS │
│            ┆            ┆          ┆           ┆   ┆           ┆          ┆          ┆ FALSELY   │
│            ┆            ┆          ┆           ┆   ┆           ┆          ┆          ┆ ELEVATES  │
│            ┆            ┆          ┆           ┆   ┆           ┆          ┆          ┆ K..       │
│ 159057461  ┆ 19999987   ┆ 23865745 ┆ 62584889  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 159057486  ┆ 19999987   ┆ 23865745 ┆ 45769962  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 159057509  ┆ 19999987   ┆ 23865745 ┆ 67447234  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
│ 159057524  ┆ 19999987   ┆ 23865745 ┆ 55471641  ┆ … ┆ 5.1       ┆ null     ┆ ROUTINE  ┆ null      │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴──────────┴──────────┴───────────┘

In [ ]:
cnpt.join(ricu, left_on=["subject_id", "time"], right_on=["subject_id", "charttime"], how="anti")

shape: (99_599, 7)
┌────────────┬──────────────┬───────────────┬───────────────┬────────────┬──────────┬───────────┐
│ subject_id ┆ time         ┆ code          ┆ numeric_value ┆ text_value ┆ dataset  ┆ table     │
│ ---        ┆ ---          ┆ ---           ┆ ---           ┆ ---        ┆ ---      ┆ ---       │
│ i64        ┆ datetime[μs, ┆ str           ┆ f32           ┆ str        ┆ str      ┆ str       │
│            ┆ UTC]         ┆               ┆               ┆            ┆          ┆           │
╞════════════╪══════════════╪═══════════════╪═══════════════╪════════════╪══════════╪═══════════╡
│ 10000117   ┆ 2174-09-22   ┆ albumin//g/dL ┆ 4.7           ┆ 4.7        ┆ mimic-iv ┆ labevents │
│            ┆ 12:26:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2175-01-27   ┆ albumin//g/dL ┆ 4.7           ┆ 4.7        ┆ mimic-iv ┆ labevents │
│            ┆ 16:15:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2176-02-08   ┆ albumin//g/dL ┆ 4.9           ┆ 4.9        ┆ mimic-iv ┆ labevents │
│            ┆ 22:00:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2176-09-08   ┆ albumin//g/dL ┆ 4.9           ┆ 4.9        ┆ mimic-iv ┆ labevents │
│            ┆ 10:00:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 10000117   ┆ 2178-06-12   ┆ albumin//g/dL ┆ 4.8           ┆ 4.8        ┆ mimic-iv ┆ labevents │
│            ┆ 15:19:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ …          ┆ …            ┆ …             ┆ …             ┆ …          ┆ …        ┆ …         │
│ 19999784   ┆ 2119-06-27   ┆ albumin//g/dL ┆ 3.7           ┆ 3.7        ┆ mimic-iv ┆ labevents │
│            ┆ 05:40:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2119-07-07   ┆ albumin//g/dL ┆ 4.3           ┆ 4.3        ┆ mimic-iv ┆ labevents │
│            ┆ 17:30:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2123-04-12   ┆ albumin//g/dL ┆ 4.0           ┆ 4.0        ┆ mimic-iv ┆ labevents │
│            ┆ 12:28:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2123-05-08   ┆ albumin//g/dL ┆ 4.0           ┆ 4.0        ┆ mimic-iv ┆ labevents │
│            ┆ 10:00:00 UTC ┆               ┆               ┆            ┆          ┆           │
│ 19999784   ┆ 2124-07-22   ┆ albumin//g/dL ┆ 4.3           ┆ 4.3        ┆ mimic-iv ┆ labevents │
│            ┆ 15:25:00 UTC ┆               ┆               ┆            ┆          ┆           │
└────────────┴──────────────┴───────────────┴───────────────┴────────────┴──────────┴───────────┘

In [ ]:
# ricu.join(cnpt, left_on=["subject_id", "charttime", "valuenum"], right_on=["subject_id", "time", "numeric_value"], how="anti")

In [ ]:
# cnpt.join(ricu, left_on=["subject_id", "time", "numeric_value"], right_on=["subject_id", "charttime", "valuenum"], how="anti")